### PR TITLE
display interrests and intrests selcotor for users

### LINKED ISSUE #34: interests list for users
**Task title**
interrests list

**Task description**
allow user to select a number of interests from our interests list
this can also be added in the event

**Subtasks**

- [x] list interest inside the edit profile
- [x] make the list selective
- [x] push the interrests array to the data base

**Screenshots**
image

**Link to the component on Figma**
Put the link here

### PR DESCRIPTION
**Pull request by HachemBouhadede**
display a user interests in their profile page
add an interest selector in the edit profile page
enhance user profile editing experience (with place holder and user's available data)
improve code quality by adding main function in controller for firebase based functions

BREAKING CHANGE: enhance code quality, improved user experience

#34

implemenetation into creat/edit event post poned untill disccussed

# Related Issue

- Resolve #34

### CODE REVIEW

**Review by Khalil-NOUI — COMMENTED** [review]
can please you confirm whether this is only rendering for me or also to everyone else ??
Screenshot (142)

**Comment by HachemBouhadede** [comment]
> can please you confirm whether this is only rendering for me or also to everyone else ?? Screenshot (142)

thanks for the heads up @Khalil-NOUI i have no idea what it is, it is working perfectly fine in the local host btw, but not in the deployment
i'll be invistigating it

**Comment by HachemBouhadede** [comment]
profile interrests list availble now, working on the edit profile one

**Comment by HachemBouhadede** [comment]
issue fixed 🙂🚀 🙂🚀 🙂🚀 🙂🚀 🙂🚀 🙂🚀  that took sometime but all for the greater good ! i'm honestly still not sure what was causing the issue, but i changed the handle selector logic

**Review by oualidelh — APPROVED** [review]
great work keep up

**Pull request merged**
