### PR TITLE
fix(howitworks, navbar, sectiontwo, common): improve display, transla…

### LINKED ISSUE #120: fix HomePage Carousel and Navbar
homepage carousel doesn't display correctly for small screens as the navbar as well

### PR DESCRIPTION
**Pull request by Khalil-NOUI**
improve display, translation

resolves #120

# Related Issue

- Resolve #120

### CODE REVIEW

**Comment by Khalil-NOUI** [comment]
navbar dont show for smallscreen with controls in the bottom

**Comment by Khalil-NOUI** [comment]
merge after meeting

**Comment by Khalil-NOUI** [comment]
@HachemBouhadede @oualidelh @iman-om  all good to merge

**Review by HachemBouhadede — APPROVED** [review]
good work khalilou, 
nothing to comment on anything cz there's nothing i can that benifits the code, GGs , i didn't check the preview for internet reason (4g is slow atm), but good work <3

**Pull request merged**
