### PR TITLE
feat(signup/signin): enable authentication providers

### LINKED ISSUE #32: Google and Twitter Auth, User
**Task title**
database and authentication management

**Task description**
allow user to SignUp and SignIn using Different authentications prooviders e.g Google, Twitter, 

**Subtasks**
- organize Collection
- enable Google Auth
- enable Twitter Auth

**Screenshots**
Screenshot 2023-10-18s
Authentication – Firebase console

**Link to the component on Figma**
https://www.figma.com/file/JNQvtNrU6LnBlRMjJ9qeYx/Pebble-work-(Copy)?type=design&node-id=5173-3073&mode=design&t=U8MTu0d4xWju4klK-4

### PR DESCRIPTION
**Pull request by Khalil-NOUI**
twiiterPebble – Authentication – Firebase console
twitterPebble – Cloud Firestore – Firebase console
AllAuthentication – Firebase console
facebook-Authentication – Firebase console
twitter– Cloud Firestore – Firebase console
allow user to sign up with Facebook, Twitter, Google

BREAKING CHANGE: enable the user to signUp/In with facebook, twitter , google accounts.

closes #32

# Related Issue

- Resolve #32

### CODE REVIEW

**Comment by HachemBouhadede** [comment]
@Khalil-NOUI does the preview sign ups work on ur end ? couldn't use any of the new sign up

**Comment by HachemBouhadede** [comment]
> @Khalil-NOUI does the preview sign ups work on ur end ? couldn't use any of the new sign up

fixed in firebase, domain authorization issue ~

**Comment by Khalil-NOUI** [comment]
i trust everything is good now, Ready to Merge, Thanks TeamNine

**Review by HachemBouhadede — APPROVED** [review]
great ya tanin !

**Comment by Khalil-NOUI** [comment]
Update !!!
the Facebook authentication will only be available to accounts assigned in the app roles in the meta developing platform.
for the the Facebook login to be available to all users, we must provide real time business documents for verification

link : https://developers.facebook.com/blog/post/2023/02/01/developer-platform-requiring-business-verification-for-advanced-access/

**Comment by Khalil-NOUI** [comment]
Facebook login  functionality removed until further solution exists

**Pull request merged**
